# Generated by Django 6.0.5 on 2026-05-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
