# Generated by Django 6.0.5 on 2026-05-13 19:16

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del recurso')),
                ('slug', models.SlugField(unique=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('short_description', models.CharField(max_length=255, verbose_name='Descripción corta')),
                ('long_description', models.TextField(verbose_name='Descripción larga')),
                ('official_site', models.URLField(blank=True, null=True, verbose_name='Sitio Oficial')),
                ('others_repositories', models.TextField(blank=True, null=True, verbose_name='Otros repositorios (GitHub, GitLab, etc.)')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versión actual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_manuals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.manual', verbose_name='Manual relacionado')),
            ],
        ),
    ]
