# Generated by Django 6.0.5 on 2026-05-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_category_resource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Imagen (URL)'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='others_repositories',
            field=models.TextField(blank=True, help_text='Un enlace por línea. Formatos válidos: https://... | Etiqueta | Fuente', null=True, verbose_name='Enlaces de descarga'),
        ),
    ]
